services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./back-end
    image: marinatraba/undersounds-backend:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/undersounds
      - BASE_URL=http://backend:5000
    expose:
      - "5000"
    env_file:
      - ./back-end/.env
    depends_on:
      - mongo
    deploy:
      replicas: 3

  frontend:
    build: 
      context: ./front-end
      args:
        - VITE_API_URL=http://localhost:8081
    image: marinatraba/undersounds-frontend:latest
    ports:
      #- "3000:3000"
      - "8082:8080"
    depends_on:
      - backend
    environment:
        - REACT_APP_API_URL=http://localhost:8081

  nginx:
    image: nginx:latest
    volumes:
      - ./back-end/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80" # Ahora el API entra por el puerto 8081
    depends_on:
      - backend

volumes:
  mongo_data: