name: Pipeline de Mi Proyecto

on:
  push:
    branches: [ "main", "master" ]

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login en ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y subir imagen a ECR
        run: |
          # Cambiado contexto a ./back-end y ruta de Dockerfile a back-end/Dockerfile
          docker build -t undersounds-backend -f back-end/Dockerfile ./back-end
          docker tag undersounds-backend:latest 756696761399.dkr.ecr.eu-north-1.amazonaws.com/undersounds-backend:latest
          docker push 756696761399.dkr.ecr.eu-north-1.amazonaws.com/undersounds-backend:latest

      - name: Registrar nueva definición de tarea
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: backend-container
          image: 756696761399.dkr.ecr.eu-north-1.amazonaws.com/undersounds-backend:latest

      - name: Despliegue Blue/Green a ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: backend-service-bg
          cluster: cluster-undersounds2
          wait-for-service-stability: true
          # Asegúrate de que el nombre del archivo en tu repo sea exactamente este:
          codedeploy-appspec: appspec.yaml
          codedeploy-application: AppECS-cluster-undersounds2-backend-service-bg
          codedeploy-deployment-group: DgpECS-cluster-undersounds2-backend-service-bg
