name: Pipeline de Mi Proyecto

on:
  push:
    branches: [ "main", "master" ]

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login en ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y subir imagen a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # 1. Nos movemos a la carpeta para no pesar gigas
          cd back-end
          
          # 2. Compilamos apuntando a tu registro de AWS
          docker build -t $ECR_REGISTRY/undersounds-backend:latest .
          
          # 3. Empujamos la imagen a la nube
          docker push $ECR_REGISTRY/undersounds-backend:latest

      # AQUÍ ESTÁ TU NUEVO DESPLIEGUE SEGURO (Sustituye al viejo)
      - name: Forzar despliegue Blue/Green en Amazon ECS
        run: |
          aws ecs update-service --cluster cluster-undersounds2 --service backend-service-bg --force-new-deployment --region eu-north-1